<a href="https://colab.research.google.com/github/AbdulHalimKhan/Image_Filtering/blob/main/Weight_Calculation_for_Gaussian_Filter_for_Image_Processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import math

def gaussian(x, y, sigma):
    """Compute the value of a Gaussian function at position (x, y)."""
    return 1 / (2 * math.pi * sigma ** 2) * math.exp(-(x ** 2 + y ** 2) / (2 * sigma ** 2))

def generate_gaussian_filter(rows, cols, sigma):
    """Generate a Gaussian filter weight matrix."""
    center_x = rows // 2
    center_y = cols // 2

    weights = np.zeros((rows, cols))

    for i in range(rows):
        for j in range(cols):
            x = i - center_x
            y = j - center_y
            weights[i][j] = gaussian(x, y, sigma)

    # Normalize the weights explicitly
    weights /= np.sum(weights)

    return weights

def main():
    rows = int(input("Enter the number of rows: "))
    cols = int(input("Enter the number of columns: "))
    sigma = float(input("Enter the standard deviation (sigma) for the Gaussian filter: "))

    # Generate the Gaussian filter weight matrix
    weights = generate_gaussian_filter(rows, cols, sigma)

    print("Gaussian filter weight matrix:")
    print(weights)

if __name__ == "__main__":
    main()


Enter the number of rows: 3
Enter the number of columns: 3
Enter the standard deviation (sigma) for the Gaussian filter: 1
Gaussian filter weight matrix:
[[0.07511361 0.1238414  0.07511361]
 [0.1238414  0.20417996 0.1238414 ]
 [0.07511361 0.1238414  0.07511361]]


In [ ]:
import numpy as np
import math

def gaussian(x, y, sigma):
    """Compute the value of a Gaussian function at position (x, y)."""
    return 1 / (2 * math.pi * sigma ** 2) * math.exp(-(x ** 2 + y ** 2) / (2 * sigma ** 2))

def generate_gaussian_filter(rows, cols, sigma):
    """Generate a Gaussian filter weight matrix."""
    center_x = rows // 2
    center_y = cols // 2

    weights = np.zeros((rows, cols))

    for i in range(rows):
        for j in range(cols):
            x = i - center_x
            y = j - center_y
            weights[i][j] = gaussian(x, y, sigma)

    # Normalize the weights based on the minimum value
    min_value = np.min(weights)
    weights /= min_value

    return weights

def main():
    rows = int(input("Enter the number of rows: "))
    cols = int(input("Enter the number of columns: "))
    sigma = float(input("Enter the standard deviation (sigma) for the Gaussian filter: "))

    # Generate the Gaussian filter weight matrix
    weights = generate_gaussian_filter(rows, cols, sigma)

    print("Gaussian filter weight matrix:")
    print(weights)

if __name__ == "__main__":
    main()


Enter the number of rows: 3
Enter the number of columns: 3
Enter the standard deviation (sigma) for the Gaussian filter: 1
Gaussian filter weight matrix:
[[1.         1.64872127 1.        ]
 [1.64872127 2.71828183 1.64872127]
 [1.         1.64872127 1.        ]]
